# Generated by Django 5.0.6 on 2024-07-08 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SymbolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument_token', models.CharField(max_length=50, unique=True)),
                ('tradingsymbol', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('exchange', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=50)),
                ('instrument_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Trading Instrument',
                'verbose_name_plural': 'Trading Instruments',
                'ordering': ['expiry'],
            },
        ),
        migrations.CreateModel(
            name='DeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Device Token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='app_devicet_user_id_c26508_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Threshold Price')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.symboldata')),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='app_subscri_user_id_fcedd3_idx'), models.Index(fields=['symbol'], name='app_subscri_symbol__ebe4b8_idx')],
                'unique_together': {('user', 'symbol')},
            },
        ),
    ]
