# Generated by Django 5.0.6 on 2024-07-10 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='alert_type',
            field=models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email'), ('Notification', 'Notification')], default='Notification', max_length=15, verbose_name='Alert Type'),
        ),
    ]
