# Generated by Django 5.0.6 on 2024-06-27 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicetoken',
            name='token',
            field=models.CharField(max_length=255, unique=True, verbose_name='Device Token'),
        ),
        migrations.AlterField(
            model_name='devicetoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='symbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='app.symbol'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='threshold_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Threshold Price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Symbol Name'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('user', 'symbol')},
        ),
        migrations.AddIndex(
            model_name='devicetoken',
            index=models.Index(fields=['user'], name='app_devicet_user_id_c26508_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user'], name='app_subscri_user_id_fcedd3_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['symbol'], name='app_subscri_symbol__ebe4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='symbol',
            index=models.Index(fields=['name'], name='app_symbol_name_75fecd_idx'),
        ),
    ]
